[toolchain]
# The nightly toolchain is needed so the generated wasm generates
# a shared memory (via +atomics) instead of a non-shared one (default behavior)
#
# Notice that since 2025-10-01, shared memory is not turned on automatically
# (see https://github.com/rust-lang/rust/pull/147225).
# It has to be enabled separately in `.cargo/config.toml`.
#
channel = "nightly-2026-01-28"
targets = ["wasm32-unknown-unknown", "wasm32-wasi"]
components = ["rust-src", "rustfmt", "clippy"]
