//! Execute code from a running WebAssembly instance on another thread.

#![allow(clippy::borrowed_box)] // Generated by derivative

use anyhow::Context;
use bytes::Bytes;
use derivative::Derivative;
use wasm_bindgen::JsValue;
use wasmer::{js::AsJs, Memory, MemoryType, Module, Store};
use wasmer_wasix::{
    runtime::task_manager::{
        SpawnMemoryTypeOrStore, TaskWasm, TaskWasmPreRun, TaskWasmRecycle, TaskWasmRun,
        TaskWasmRunProperties, WasmResumeTrigger,
    },
    wasmer_wasix_types::wasi::ExitCode,
    StoreSnapshot, WasiEnv, WasiFunctionEnv, WasiThreadError,
};

use crate::tasks::SchedulerMessage;

pub(crate) fn to_scheduler_message(
    task: TaskWasm,
) -> Result<SchedulerMessage, WasiThreadError> {
    let TaskWasm {
        callbacks,
        env,
        module,
        spawn_type,
        update_layout,
        globals,
        ..
    } = task;

    let module_bytes = module.serialize().unwrap_or_default();

    let (memory_ty, memory, run_type) = match spawn_type {
        wasmer_wasix::runtime::SpawnType::CreateMemory => {
            (None, None, WasmMemoryType::CreateMemory)
        }
        wasmer_wasix::runtime::SpawnType::CreateMemoryOfType(ty) => {
            (Some(ty), None, WasmMemoryType::CreateMemoryOfType(ty))
        }
        wasmer_wasix::runtime::SpawnType::AttachMemory(m) => {
            let mut store = Store::default();
            let m = m.attach(&mut store);
            let ty = m.ty(&store);
            let memory = m.as_jsvalue(&store);
            (
                Some(ty),
                Some(memory),
                WasmMemoryType::ShareMemory(m.ty(&store)),
            )
        },
        wasmer_wasix::runtime::SpawnType::NewLinkerInstanceGroup(..) => todo!()
    };

    let memory = memory.map(|m| {
        // HACK: The store isn't used when converting memories, so it's fine to
        // use a dummy one.
        let mut store = wasmer::Store::default();
        let ty = memory_ty.expect("Guaranteed to be set");
        match wasmer::Memory::from_jsvalue(&mut store, &ty, &m) {
            Ok(m) => m,
            Err(_) => unreachable!(),
        }
    });

    let store_snapshot = globals.clone();
    let spawn_wasm = SpawnWasm {
        trigger: callbacks.trigger.map(|trigger| WasmRunTrigger {
            run: trigger,
            memory_ty: memory_ty.expect("triggers must have the a known memory type"),
            env: env.clone(),
        }),
        run: callbacks.run,
        pre_run: callbacks.pre_run,
        run_type,
        env,
        module_bytes,
        update_layout,
        result: None,
        recycle: callbacks.recycle,
        store_snapshot,
    };

    Ok(SchedulerMessage::SpawnWithModuleAndMemory {
        module,
        memory,
        spawn_wasm,
    })
}

#[derive(Debug, Clone)]
pub(crate) enum WasmMemoryType {
    CreateMemory,
    CreateMemoryOfType(MemoryType),
    ShareMemory(MemoryType),
}

#[derive(Derivative)]
#[derivative(Debug)]
struct WasmRunTrigger {
    #[derivative(Debug(format_with = "crate::utils::hidden"))]
    run: Box<WasmResumeTrigger>,
    memory_ty: MemoryType,
    env: WasiEnv,
}

#[derive(Derivative)]
#[derivative(Debug)]
pub(crate) struct SpawnWasm {
    /// An async callback to perform before running.
    #[derivative(Debug(format_with = "crate::utils::hidden"))]
    pre_run: Option<Box<TaskWasmPreRun>>,
    /// A blocking callback to run.
    #[derivative(Debug(format_with = "crate::utils::hidden"))]
    run: Box<TaskWasmRun>,
    /// How the memory should be instantiated to execute the [`SpawnWasm::run`]
    /// callback.
    run_type: WasmMemoryType,
    env: WasiEnv,
    /// The raw bytes for the WebAssembly module being run.
    #[derivative(Debug(format_with = "crate::utils::hidden"))]
    module_bytes: Bytes,
    /// A snapshot of the instance store, used to fork from existing instances.
    store_snapshot: Option<StoreSnapshot>,
    /// An asynchronous callback which is used to run asyncify methods. The
    /// returned value is used in [`wasmer_wasix::rewind()`] or instant
    /// responses.
    trigger: Option<WasmRunTrigger>,
    update_layout: bool,
    /// The result of running the trigger.
    result: Option<Result<Bytes, ExitCode>>,
    #[derivative(Debug(format_with = "crate::utils::hidden"))]
    recycle: Option<Box<TaskWasmRecycle>>,
}

impl SpawnWasm {
    pub(crate) fn module_bytes(&self) -> Bytes {
        self.module_bytes.clone()
    }

    pub(crate) fn shared_memory_type(&self) -> Option<MemoryType> {
        match self.run_type {
            WasmMemoryType::ShareMemory(ty) => Some(ty),
            WasmMemoryType::CreateMemory | WasmMemoryType::CreateMemoryOfType(_) => None,
        }
    }

    /// Prepare the WebAssembly task for execution, waiting for any triggers to
    /// resolve.
    pub(crate) async fn begin(mut self) -> ReadySpawnWasm {
        if let Some(trigger) = self.trigger.take() {
            self.result = Some((trigger.run)().await);
        }

        crate::fs::hooks::Hooks::trigger_initiated(&self.env);

        ReadySpawnWasm(self)
    }
}

/// A [`SpawnWasm`] instance that is ready to be executed.
#[derive(Debug)]
pub struct ReadySpawnWasm(SpawnWasm);

impl ReadySpawnWasm {
    /// Execute the callback, blocking until it has completed.
    pub(crate) async fn execute(
        self,
        wasm_module: js_sys::WebAssembly::Module,
        wasm_memory: JsValue,
    ) -> Result<(), anyhow::Error> {
        let ReadySpawnWasm(SpawnWasm {
            pre_run,
            run,
            run_type,
            env,
            module_bytes,
            update_layout,
            result,
            trigger: _,
            recycle,
            store_snapshot,
        }) = self;

        // Invoke the callback which will run the web assembly module
        let (mut ctx, mut store) = build_ctx_and_store(
            wasm_module,
            wasm_memory,
            module_bytes,
            env,
            store_snapshot,
            run_type,
            update_layout,
        )
        .context("Unable to initialize the context and store")?;

        if let Some(pre_run) = pre_run {
            pre_run(&mut ctx, &mut store).await;
        }

        let properties = TaskWasmRunProperties {
            ctx,
            store,
            trigger_result: result,
            recycle,
        };
        run(properties);

        Ok(())
    }
}

fn build_ctx_and_store(
    module: js_sys::WebAssembly::Module,
    memory: JsValue,
    module_bytes: Bytes,
    env: WasiEnv,
    store_snapshot: Option<StoreSnapshot>,
    run_type: WasmMemoryType,
    update_layout: bool,
) -> Option<(WasiFunctionEnv, Store)> {
    // Compile the web assembly module
    let module: Module = (module, module_bytes).into();

    //web_sys::console::warn_3(&"task_wasm".into(), &format!("{:?}", run_type).into(), &memory);

    // Make a fake store which will hold the memory we just transferred
    let mut temp_store = env.runtime().new_store();
    let spawn_type = match run_type {
        WasmMemoryType::CreateMemory => SpawnMemoryTypeOrStore::New,
        WasmMemoryType::CreateMemoryOfType(mem) => SpawnMemoryTypeOrStore::Type(mem),
        WasmMemoryType::ShareMemory(ty) => {
            let memory = match Memory::from_jsvalue(&mut temp_store, &ty, &memory) {
                Ok(a) => a,
                Err(_) => {
                    tracing::error!("Failed to receive memory for module");
                    return None;
                }
            };
            SpawnMemoryTypeOrStore::StoreAndMemory(temp_store, memory)
        }
    };

    let (ctx, store) = match WasiFunctionEnv::new_with_store(
        module,
        env,
        store_snapshot,
        spawn_type,
        update_layout,
        false,  /* call_initialize */
        None
    ) {
        Ok(a) => a,
        Err(err) => {
            tracing::error!(
                error = &err as &dyn std::error::Error,
                "Failed to create wasi context",
            );
            return None;
        }
    };
    Some((ctx, store))
}
